name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build SITEURL=https://www.analyticstxt.org
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./output
          user_name: hioffen
          user_email: hioffen@posteo.de
          cname: www.analyticstxt.org
