name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      OFFEN_ACCOUNT_ID: e52e7c55-4132-4ad3-a50b-2c1ce577a48e
      SITEURL: https://www.analyticstxt.org
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          user_name: hioffen
          user_email: hioffen@posteo.de
          cname: www.analyticstxt.org
